module SearchableRecord

  extend ActiveSupport::Concern
  included do
      after_save :reindex, if: proc { |model| model.previous_changes.key?("title_ru") || model.previous_changes.key?("title_en") }
      searchkick word_start: [:title_en, :title_ru],
                 suggest: [:title_en, :title_ru],
                 merge_mappings: true, settings: {
          "index.mapping.total_fields.limit": 50000,
          analysis: {
              char_filter: {
                  RUS_EN_key: {
                      type: "mapping",
                      mappings: [
                          "a => ф",
                          "b => и",
                          "c => с",
                          "d => в",
                          "e => у",
                          "f => а",
                          "g => п",
                          "h => р",
                          "i => ш",
                          "j => о",
                          "k => л",
                          "l => д",
                          "m => ь",
                          "n => т",
                          "o => щ",
                          "p => з",
                          "r => к",
                          "s => ы",
                          "t => е",
                          "u => г",
                          "v => м",
                          "w => ц",
                          "x => ч",
                          "y => н",
                          "z => я",
                          "A => Ф",
                          "B => И",
                          "C => С",
                          "D => В",
                          "E => У",
                          "F => А",
                          "G => П",
                          "H => Р",
                          "I => Ш",
                          "J => О",
                          "K => Л",
                          "L => Д",
                          "M => Ь",
                          "N => Т",
                          "O => Щ",
                          "P => З",
                          "R => К",
                          "S => Ы",
                          "T => Е",
                          "U => Г",
                          "V => М",
                          "W => Ц",
                          "X => Ч",
                          "Y => Н",
                          "Z => Я",
                          "[ => х",
                          "] => ъ",
                          "; => ж",
                          ", => б",
                          ". => ю",
                          "' => э",
                          "я => z",
                          "ф => a",
                          "й => q",
                          "ц => w",
                          "ы => s",
                          "ч => x",
                          "у => e",
                          "в => d",
                          "с => c",
                          "к => r",
                          "а => f",
                          "м => v",
                          "е => t",
                          "п => g",
                          "и => b",
                          "н => y",
                          "р => h",
                          "т => n",
                          "г => u",
                          "о => j",
                          "ь => m",
                          "ш => i",
                          "л => k",
                          "б => ,",
                          "щ => o",
                          "д => l",
                          "ю => .",
                          "з => p",
                          "ж => ;",
                          "х => [",
                          "э => '",
                          "ъ => ]",
                          "Я => Z",
                          "Ф => A",
                          "Й => Q",
                          "Ц => W",
                          "Ы => S",
                          "Ч => X",
                          "У => E",
                          "В => D",
                          "С => C",
                          "К => R",
                          "А => F",
                          "М => V",
                          "Е => T",
                          "П => G",
                          "И => B",
                          "Н => Y",
                          "Р => H",
                          "Т => N",
                          "Г => U",
                          "О => J",
                          "Ь => M",
                          "Ш => I",
                          "Л => K",
                          "Б => ,",
                          "Щ => O",
                          "Д => L",
                          "Ю => .",
                          "З => P",
                          "Ж => ;",
                          "Х => [",
                          "Э => '",
                          "Ъ => ]"
                      ]
                  }
              },
              analyzer: {
                  RUS_EN_key_analyzer: {
                      char_filter: [
                          "RUS_EN_key"
                      ],
                      tokenizer: "standard",
                      token_filter: ["lowercase"]
                  }
              }
          }
      }
    end

end
